import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Test() {
  const router = useRouter()
  const handleClick = (e) => {
    e.preventDefault()
    router.push("/")
  }
  // 17.3.0
  return (
    <>
      <Head>
        <title>Create Next Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        Test
        <p onClick={(e)=> handleClick(e)}>
            Back to home
          </p>
      </main>
    </>
  )
}
